openapi: 3.0.0
info:
  description: A simple API to retrieve user data.
  title: User API
  version: 1.0.0
servers:
- url: /
paths:
  /users/{userId}:
    get:
      parameters:
      - explode: false
        in: path
        name: userId
        required: true
        schema:
          format: int64
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
          description: OK
      summary: Returns a user by ID.
components:
  schemas:
    User:
      example:
        name: Arthur Dent
        id: 4
      properties:
        id:
          example: 4
          title: id
          type: integer
        name:
          example: Arthur Dent
          title: name
          type: string
      required:
      - id
      - name
      title: User
      type: object
